# Generated by Django 4.1.6 on 2023-02-04 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_activation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='money',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
        migrations.DeleteModel(
            name='InfoUser',
        ),
    ]
