# Generated by Django 4.1.6 on 2023-03-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_review_rating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
        migrations.RemoveField(
            model_name='savedcourse',
            name='saved',
        ),
    ]
