# Generated by Django 4.1.6 on 2023-03-21 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Lesson name')),
                ('description', models.TextField(verbose_name='Lesson Description')),
                ('topic', models.TextField(verbose_name='topic')),
                ('code', models.TextField(verbose_name='code')),
                ('file', models.FileField(upload_to='lessonfile/', verbose_name='File with code in the format --> MD')),
                ('video', models.FileField(blank=True, upload_to='videolesson/', verbose_name='Video')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
