# Generated by Django 4.1.6 on 2023-05-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_alter_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(upload_to='lessonfile/', verbose_name='File with code'),
        ),
    ]
